### PR TITLE
Update to libp8-platform

### PR DESCRIPTION
**Pull request by hudokkow**
Prepare switch to libp8-platform-dev

### CODE REVIEW

**Comment by hudokkow** [comment]
Time to merge?

**Comment by notspiff** [comment]
this has no buildsystem changes ?

sorry if i miss things and whatnot, friggan gmail is driving me insane with late deliveries, threading of unrelated shit and whatnot.

**Comment by hudokkow** [comment]
Nope, no changes. CMakeLists.txt doesn't mention lib(p8)-platform. I guess we're relying on libkodiplatform to actually get lib(p8)-platform.
I guess the proper solution is to explicitly ask for libp8-platform since we don't need libkodiplatform.

**Comment by hudokkow** [comment]
Updated

**Pull request merged**
